M48
; DRILL file {KiCad 8.0.5} date 2024-09-18T00:43:06+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-09-18T00:43:06+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X108.9Y-96.0
X108.9Y-110.0
X126.9Y-110.0
X127.0Y-96.0
T2
X79.0Y-73.5
X79.0Y-113.5
X144.0Y-73.5
X144.0Y-113.5
M30
